{{- if include "connector.enabled" . | eq "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
spec:
{{- if not .Values.connector.autoscaling.enabled }}
  replicas: {{ .Values.connector.replicas }}
{{- end }}
  selector:
    matchLabels:
{{- include "connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "connector.podLabels" . | nindent 8 }}
      annotations:
{{- include "connector.podAnnotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.connector.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "connector.serviceAccountName" . }}
      imagePullSecrets:
{{- include "connector.imagePullSecrets" . | nindent 8 }}
      securityContext:
{{- toYaml .Values.connector.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.connector.componentName }}
          securityContext:
{{- toYaml .Values.connector.securityContext | nindent 12 }}
          image: "{{ include "connector.image.repository" . }}:{{ include "connector.image.tag" . }}"
          imagePullPolicy: {{ include "connector.image.pullPolicy" . }}
          args:
            - connector
            - -f
            - /etc/infrahq/infra.yaml
# set log level through command line parameters since its not possible to set using configuration file values
{{- with .Values.connector.config.logLevel }}
            - --log-level
            - {{ . }}
{{- end }}
          env:
{{- include "connector.env" . | nindent 12 }}
          envFrom:
{{- include "connector.envFrom" . | nindent 12 }}
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
            - name: conf
              mountPath: /etc/infrahq
              readOnly: true
{{- if and (not .Values.connector.config.caCert) (not .Values.connector.config.caKey) }}
            - name: ca
              mountPath: /var/run/secrets/infrahq.com/ca
{{- end }}
            - name: access-key
              mountPath: /var/run/secrets/infrahq.com/access-key
{{- if .Values.connector.volumeMounts }}
{{- toYaml .Values.connector.volumeMounts | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.connector.config.addr.http }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.connector.config.addr.https }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.connector.config.addr.metrics }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.connector.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.connector.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.connector.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.connector.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.connector.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.connector.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.connector.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.connector.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.connector.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.connector.readinessProbe.timeoutSeconds }}
          resources:
{{- toYaml .Values.connector.resources | nindent 12 }}
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conf
          configMap:
            name: {{ include "connector.fullname" . }}
{{- if and (not .Values.connector.config.caCert) (not .Values.connector.config.caKey) }}
        - name: ca
          secret:
            secretName: {{ include "connector.fullname" . }}-ca
{{- end }}
        - name: access-key
          secret:
            secretName: {{ .Release.Name }}-access-key
            optional: true
{{- if .Values.connector.volumes }}
{{- toYaml .Values.connector.volumes | nindent 8 }}
{{- end }}
{{- with .Values.connector.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.connector.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.connector.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
