{{- if include "server.enabled" . | eq "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
{{- include "server.labels" . | nindent 4 }}
spec:
{{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicas }}
{{- end }}
  selector:
    matchLabels:
{{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "server.podLabels" . | nindent 8 }}
      annotations:
{{- include "server.podAnnotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.server.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      imagePullSecrets:
{{- include "server.imagePullSecrets" . | nindent 8 }}
      securityContext:
{{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.server.componentName }}
          securityContext:
{{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ include "server.image.repository" . }}:{{ include "server.image.tag" . }}"
          imagePullPolicy: {{ include "server.image.pullPolicy" . }}
          args:
            - server
            - -f
            - /etc/infrahq/infra.yaml
{{ if .Values.ui.enabled }}
            - --ui-proxy-url
            - http://{{ include "ui.fullname" . }}.{{ .Release.Namespace }}:3000
{{- end}}
# set log level through command line parameters since its not possible to set using configuration file values
{{- with .Values.server.config.logLevel }}
            - --log-level
            - {{ . }}
{{- end }}
          env:
{{- include "server.env" . | nindent 12 }}
          envFrom:
{{- include "server.envFrom" . | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: /etc/infrahq
              readOnly: true
{{- if (not .Values.server.config.tls) }}
            - name: tls-ca
              mountPath: /var/run/secrets/infrahq.com/tls-ca
{{- end }}
{{- if .Values.server.persistence.enabled }}
            - name: data
              mountPath: /var/lib/infrahq/server
{{- end }}
{{- if .Values.server.volumeMounts }}
{{- toYaml .Values.server.volumeMounts | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
          resources:
{{- toYaml .Values.server.resources | nindent 12 }}
{{- if .Values.server.persistence.enabled }}
      initContainers:
        - name: chown-sqlite3
          image: alpine:latest
          command: [sh, -c]
          args:
            - 'find /var/lib/infrahq/server -type f -name "sqlite3.*" -exec chown $RUN_AS_USER:$RUN_AS_GROUP {} \;'
          env:
            - name: RUN_AS_USER
              value: "{{ .Values.server.securityContext.runAsUser | default .Values.server.podSecurityContext.runAsUser | default 1000 }}"
            - name: RUN_AS_GROUP
              value: "{{ .Values.server.securityContext.runAsGroup | default .Values.server.podSecurityContext.runAsGroup | default 1000 }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/infrahq/server
{{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "server.fullname" . }}
{{- if (not .Values.server.config.tls) }}
        - name: tls-ca
          secret:
            secretName: {{ include "server.fullname" . }}-ca
{{- end }}
{{- if .Values.server.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "server.fullname" . }}
{{- end }}
{{- if .Values.server.volumes }}
{{- toYaml .Values.server.volumes | nindent 8 }}
{{- end }}
{{- with .Values.server.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.server.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.server.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
