{{- if .Values.server.enabled }}
{{- if .Values.server.ingress.enabled }}
{{- if and .Values.server.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
{{- if not (hasKey .Values.server.ingress.annotations "kubernetes.io/ingress.class") }}
{{- $_ := set .Values.server.ingress.annotations "kubernetes.io/ingress.class" .Values.server.ingress.className}}
{{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "server.fullname" . }}
  labels:
{{- include "server.labels" . | nindent 4 }}
{{- if .Values.server.ingress.labels }}
{{- toYaml .Values.server.ingress.labels | nindent 4 }}
{{- end }}
  annotations:
{{- toYaml .Values.server.ingress.annotations | nindent 4 }}
spec:
{{- if and .Values.server.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.server.ingress.className }}
{{- end }}
{{- if .Values.server.ingress.tls }}
  tls:
{{- range .Values.server.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
{{- range .hosts }}
        - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
  rules:
{{- range .Values.server.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
{{- range $.Values.server.ingress.paths }}
          - path: {{ . }}
{{- if and $.Values.server.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $.Values.server.ingress.pathType }}
{{- end }}
            backend:
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "server.fullname" $ }}
                port:
                  number: {{ $.Values.server.service.port }}
{{- else }}
              serviceName: {{ include "server.fullname" $ }}
              servicePort: {{ $.Values.server.service.port }}
{{- end }}
{{- end }}
{{- if $.Values.server.ingress.additionalPaths }}
{{- toYaml $.Values.server.ingress.additionalPaths | nindent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
